version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER : admin
      POSTGRES_DB : application
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  application:
    build: .
    ports:
      - 8000:8000
    restart : always

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    volumes:
      - ./cloudbeaver-data:/opt/cloudbeaver/workspace
    restart: unless-stopped
    depends_on: 
      - db

volumes:
  postgres_data:
